### ISSUE TITLE
Plugin seems to continually sit in the background using a fair chunk of CPU

### ISSUE THREAD

**Issue by micpp42** [FriendsOfGalaxy/galaxy-integration-steam#10]
Hi,
With this plugin running there seems to be a Python process sitting in the background that's constantly using like 28%ish CPU (and a small amount of network bandwidth). I'm pretty sure it's related to the plugin since force closing it makes Galaxy say that the Steam plugin has crashed (and it comes back when I restart the plugin).
What's it doing to take up that chunk of CPU continuously?

**Comment by bjab** [comment]
There are two issues, as I see:

1. logging is set to debug, so plugin is constantly writing to log file
1. plugin scans steam directory for installed games every second

**Comment by Elikay** [comment]
This issue seems to have been related to a bug within the Galaxy 2.0 API, and should be fixed, anyone still having issues should try reinstalling the plugin if needed, and see if it's fixed.

**Comment by micpp42** [comment]
A quick check suggests it still seems to be happening to a certain extent (plugin was sitting there using about 14% cpu with nothing happening)... but I will try again later in case the update has not rolled out to me yet

**Comment by Elikay** [comment]
The initial startup is still a bit intensive, I may look deeper into that in the future and see if there's any optimizations that could be made. The update never pushed out for me either, I instead manually updated it. The way GOG currently handles plugins and updates isn't very consistent as far as I can tell. You can go to `AppData\Local\GOG.com\Galaxy\plugins\installed` and delete the folder there, and it should automatically redownload and update the plugin if needed.

**Comment by micpp42** [comment]
I've tried out making sure it's updated etc... while it's definitely better than before it still seems to sit there at about 15% continual CPU usage, even after the initial setup

**Comment by FriendsOfGalaxy** [comment]
@micpp42 Which plugin version do you have? You can check in logs or manifest.json file in %localappdata%\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8

Version 0.33 should be OK. For me never exceeds 0.1%

**Comment by micpp42** [comment]
It looks like with the latest GOG update this hasn't been happening any more, at least for me
