### ISSUE TITLE
Tales of berseria Achievments not synced

### ISSUE THREAD

**Issue by Tsuna77** [FriendsOfGalaxy/galaxy-integration-steam#101]
**Describe the bug**
I sync gog and steam 3 days ago, I started to play Tales of Vesperia on steam. Game time is ok (27 hours) but achievments are only seen on steam and not gog.

**To Reproduce**
Get achievments on Tales of Berseria

**Expected behavior**
Achivements updated on GoG Galaxy

**Attached logs**
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5753797/logs.zip)

**Comment by Tsuna77** [comment]
I apply the #100  to my gog galaxy.

It was solved with it. Could you merge it please :)

**Comment by Pab10Suarez** [comment]
> I apply the #100 to my gog galaxy.
> 
> It was solved with it. Could you merge it please :)

sorry i don't know how to apply a pull request could you explain it to me?
