### ISSUE TITLE
Can no longer change cover images for Steam games.

### ISSUE THREAD

**Issue by munt-kaicho** [FriendsOfGalaxy/galaxy-integration-steam#105]
For a few days now I have been unable to change cover images for games that have been added to Galaxy via the Steam integration. The other games work fine.

When I try to change the image I get an error saying "Image Override Failed. Try different image format or size."
I have tried changing image format, reducing image resolution, reducing file size by compressing the image, loading the image from a different file path. Nothing works.

**Comment by FriendsOfGalaxy** [comment]
Hi @munt-kaicho that is the Galaxy issue. Please report using Galaxy->manu->Report Issue interface
