### ISSUE TITLE
Friends Sidebar only updates on Galaxy launch

### ISSUE THREAD

**Issue by cbrookins** [FriendsOfGalaxy/galaxy-integration-steam#106]
**Describe the bug**
The steam list of friends does not update after initial launch.   Friends list shows outdated data until Galaxy is relaunched.

**To Reproduce**
1. Launch Galaxy with Friends Sidebar visible
2. Friend opens a game or comes online/offline
3. Friend closes game or comes online/offline
4. Status of that friend does not update in the Friends Sidebar
5. Completely close Galaxy and re-launch. Friends Sidebar is updated.

**Expected behavior**
I would expect the Friends Sidebar to update, if not instantly, at some consistent frequency that makes the Friends Sidebar usable and somewhat trustworthy.

**Attached logs**
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5862678/logs.zip)

**Comment by ShaunV2** [comment]
For me the Steam Friends List isn't loading at all anymore.
[Logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5877109/Logs.zip)

**Comment by FriendsOfGalaxy** [comment]
Plugin is reporting properly. Apparently something wrong with Galaxy. Could you attach GalaxyClient as well?

**Comment by cbrookins** [comment]
Submitted.
Issue ID: 0128156
