### ISSUE TITLE
Wallpaper Engine Not Appearing on GOG Galaxy

### ISSUE THREAD

**Issue by JPFlySolo** [FriendsOfGalaxy/galaxy-integration-steam#107]
Hi, so the integration seems to be working fine but it seems like I can't get Wallpaper Engine to come over. I know this is a software (not a game) but I would think it should transfer through considering it's on the game list and has achievements available. Here are the logs to see if that helps.

I also saw this reddit post that GOG fixed the issue where SteamApps (such as WallpaperEngine) is not showing on GOG Galaxy from a few months ago: https://www.reddit.com/r/gog/comments/h9lglq/gog_galaxy_20_some_common_issues_and_their/

So I'm curious to know i9f it's the integration problem or if it's GOG. Hope you can look into this. Thanks!

[Logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5869327/Logs.zip)

**Comment by FriendsOfGalaxy** [comment]
Hey, it is GOG responsibility. They tend to filter out all non-game items regardless of the source.
