### ISSUE TITLE
Certain Achievement(s) not parsed properly, likely due to a comma

### ISSUE THREAD

**Issue by ABaumher** [FriendsOfGalaxy/galaxy-integration-steam#109]
*Description:*
I have a single achievement/trophy (I'll use these interchangeably, I'm sorry about that) that will not load properly, everything else loads fine. While at first i thought this may be an issue similar to others raised here (i.e. #56), some manual debugging leads me to believe it is due to the trophy in question having a comma in it. I'm not overly familiar with the the JSON requests being sent back and forth, but am painfully aware how finicky sanitizing inputs for CSV tables or regular databases is.

*Expected Behavior:*
 All achievements load properly. 

*Actual Behavior:*
All achievements load properly except one, which has a comma in it. (Trophy: "60 down 99,999,940 to go"). The log file has this achievement loaded. 

*Steps to Reproduce:* 
1. Already have, or play and obtain an achievement that has a comma in its name, or simulate one if possible. 
2. Note that the achievement is not properly received after all data is fully loaded. 
This persists after clearing the log, as well as disconnecting and reconnecting the plugin. 

Attached logs:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5935132/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

The achievement appears to be obtained and handled properly in the log. I don't know if this is a bug here or on GoG's end. The relevant log data is here, for convenience 

```
2021-02-05 14:41:00,070 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '304410', 'unlocked_achievements': [Achievement(unlock_time=1530676874, achievement_id=None, achievement_name='World 2'), Achievement(unlock_time=1530677413, achievement_id=None, achievement_name='World 3'), Achievement(unlock_time=1530679949, achievement_id=None, achievement_name='World 4'), Achievement(unlock_time=1530681014, achievement_id=None, achievement_name='World 5'), Achievement(unlock_time=1530751364, achievement_id=None, achievement_name='World 6'), Achievement(unlock_time=1530846172, achievement_id=None, achievement_name='Perfectionist'), Achievement(unlock_time=1532322005, achievement_id=None, achievement_name='60 down 99,999,940 to go')]} 
```

**Comment by ABaumher** [comment]
The game in question causing this is "Hexcells Infinite". My profile can be viewed here [https://steamcommunity.com/profiles/76561198421339401](https://steamcommunity.com/profiles/76561198421339401). If it's helpful, use my Steam ID for testing.

**Comment by ABaumher** [comment]
Alternatively, there's a spelling mismatch - the gog page has "999,999,940" while the log and every stream page I've seen has "99,999,940". If GOG uses a string compare to unlock achievements, this would be the cause. That said, the achievement data is also pulled from Steam, so it doesn't make sense that it would return one string there and a different one here. I'd check myself, but as far as i can tell the raw achievement data for each game is not logged after its pulled from the Steam API, and I'd need a Steam API key to do so manually.

Could this all be caused by a localization? If so, could the api name for each achievement be used instead of the (potentially) localized name? 
From what i see the Achievement class in the GOG API provides a Unique ID field, which would be perfect for this, and it's currently left empty.

**Comment by FriendsOfGalaxy** [comment]
Maybe the name of the achievement was updated by dev, and gog has fetched the previous name.

> From what i see the Achievement class in the GOG API provides a Unique ID field, which would be perfect for this, and it's currently left empty.

correct, that is because we primarily used web scrapping to get achievements, and only name was available. Maybe we could use ids if steam it returns, but I'm not sure if it will work out of the box on GOG side.

**Comment by ABaumher** [comment]
Do you scrape the data from the Steam web API or just from the user's public profile page? There's a way to grab the API Name from the Steam API, and assuming GOG uses the Steam API to pull global achievement percentages, they probably do too. (They'd use GetGlobalAchievementPercentagesForApp from the ISteamUserStats interface, which uses the API Name). I don't know the underlying cause of #56, but if it is a localization issue this would fix it. I'll see if i can modify one of your test cases to check and see if GOG stores the API Name.

**Comment by ABaumher** [comment]
Updated by GOG. I'm not completely happy with this because if i could find one at random it's likely there are more, especially if we don't know why it happened in the first place. That said, it's a GOG issue, not here. 

Also, I'm likely wrong, because you can scrape the global data straight from Steam's web pages, so GOG does that.  This would be infinitely simpler if Valve played nice and gave us an official integration.

**Comment by FriendsOfGalaxy** [comment]
> Do you scrape the data from the Steam web API or just from the user's public profile page?
neither. We use steam protobuf protocols. There is no achievement names unfortunately. Only a numerical list of achievements with their names and unlock timestamps divided by sections.

Having access to steam API would be nice, but we immediately hit their API requests limits. More info here: #2 

> Also, is the source code for how GOG pulls that global data available to us to view?

No

> Updated by GOG. I'm not completely happy with this because if i could find one at random it's likely there are more, especially if we don't know why it happened in the first place. That said, it's a GOG issue, not here.

yeah, I agree. But assuming they match unlocked achievements by ID if available (see https://github.com/gogcom/galaxy-integrations-python-api/blob/master/src/galaxy/api/types.py#L129) and they know steam achievements IDs from their API, then plugin could do better by providing achievement ids.

> you can scrape the global data straight from Steam's web pages
Do you? How we can find public achievement definitions?
