### ISSUE TITLE
Steam synchronizing problems with installed games 

### ISSUE THREAD

**Issue by hightower5** [FriendsOfGalaxy/galaxy-integration-steam#112]
Synchronizing with installed and new bought steam games doesn't work anymore.

**Comment by hightower5** [comment]
Hello, can you please fix this problem?

Thank you.

**Comment by FriendsOfGalaxy** [comment]
Hey @hightower5, please follow the issue template: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by hightower5** [comment]
GOG Galaxy doesn't list any installed steam games, and it doesn't synchronize the steam database anymore.

[Steam-Logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6204011/Steam-Logs.zip)
