### ISSUE TITLE
Family sharing game doesn't show achievements

### ISSUE THREAD

**Issue by Pab10Suarez** [FriendsOfGalaxy/galaxy-integration-steam#119]
**Describe the bug**
I'm playing isaac trough family sharing but achievements dont appear in gog galaxy

**Expected behavior**
gog galaxy show isaac achievements
**Attached logs**
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6503877/logs.zip)

**Comment by FriendsOfGalaxy** [comment]
Hi @Pab10Suarez , looks like the issue is included in this one: #79

**Comment by Pab10Suarez** [comment]
thx!
