### ISSUE TITLE
Games installed on Steam, are not shown as installed on GoG Galaxy.

### ISSUE THREAD

**Issue by tfredett** [FriendsOfGalaxy/galaxy-integration-steam#121]
**Before start**
- check if your issue is known: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Common-problems
Checked the link above, as well as all issues reported, and found this to be the closest issue. https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/48

**Describe the bug**
Installed games on steam, are not registering as installed via the GoG Galaxy plugin used here. They are showing up as available titles to install. Even when attempting that, no change. (It says it is launching steam to install, nothing actually happens though)

This may be due to the fact that when this started, the steam cache on my local had gotten corrupted. Enough to the point, where I had to clear the cache completely, and restart from scratch. As a result of this, I also ended up having to clear out my registry of all the installed steam games on my local.

It should be noted that all games in the library do show up within GoG Galaxy, just none that are installed on Steam, are listed as installed on GoG Galaxy. And I am unable to change that status.

The attempts to resolve this are as follows.
1) Disconnect and reconnect the plugin.
2) Disconnect the plugin, close down Galaxy, reinstall the plugin, boot Galaxy back up, and reconnect the plugin.
3) Disconnect the plugin, reboot machine, reconnect the plugin.
4) Disconnect the plugin, uninstall GoG Galaxy, reinstall Galaxy, reconnect the plugin.
5) Disconnect the plugin, uninstall Galaxy, reboot machine, reinstall Galaxy, reconnect the plugin.

My hunch, is there is some type of local file that the plugin is using. Based on the commentary from the issue listed above, I suspected it was the `libraryfolders.vdf` file. Which was also in part replaced, during the cache corruption. (I ended up removing that file, so I could re-add a library folder. that file now exists in an almost identical fashion from what I can tell to what was there previously.)

**To Reproduce**
1. Corrupt your local steam cache.
2. Remove your entire local steam cache and rebuild it.
3. Attempt to reconnect, and observe that any installed games on steam, are not shown as installed on GoG Galaxy.

**Expected behavior**
That installed games on steam show up as installed on GoG Galaxy, and the plugin can appropriately interact with steam. (For example, to install games not currently installed, or to launch them)

**Attached logs**
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6623991/logs.zip)

Screenshots showing as an example, a game installed on steam, yet not showing as installed on Galaxy.
![not_installed_on_steam_via_gog_galaxy](https://user-images.githubusercontent.com/2530584/121361621-77fbaf00-c903-11eb-8af9-174098c2cda7.PNG)
![installed_on_steam](https://user-images.githubusercontent.com/2530584/121361622-77fbaf00-c903-11eb-94f5-55bcc2fb2b5c.PNG)

**Comment by mylemans** [comment]
Same issue here. First time installing it, so a bit disappointed ;D

Install only 'works' if it isn't actually installed yet (you get the steam install dialog then), but trying the same on a game that is already installed does nothing.

**Comment by tfredett** [comment]
> 
> 
> Same issue here. First time installing it, so a bit disappointed ;D
> 
> Install only 'works' if it isn't actually installed yet (you get the steam install dialog then), but trying the same on a game that is already installed does nothing.

Can confirm this as well. Installed a game via Galaxy on Steam. Noticed that the prompt came up, and let it install on Steam. Game status of now installed game, still shows as uninstalled on Galaxy.

**Comment by EASK8ER52** [comment]
Has anyone fixed this issue yet. Steam plugin has always worked for me but today it stopped and I'm getting the same exact issues as this Issue.

**Comment by F15htastic** [comment]
Also experiencing this issue.
Looks like Valve have changed the format of `libraryfolders.vdf`.

Now, entries have a couple of fields instead of just a path.

```"libraryfolders"
{
	"contentstatsid"		"-123456789"
	"1"
	{
		"path"		"F:\\Program Files (x86)\\Steam"
		"label"		""
		"mounted"		"1"
		"contentid"		"123456789"
	}
	"2"
	{
		"path"		"D:\\Games\\SteamLibrary"
		"label"		""
		"mounted"		"1"
		"contentid"		"123456789"
	}
	"3"
	{
		"path"		"G:\\SteamLibrary"
		"label"		""
		"mounted"		"1"
		"contentid"		"123456789"
	}
	"4"
	{
		"path"		"E:\\SteamLibrary"
		"label"		"WD Green HDD"
		"mounted"		"1"
		"contentid"		"123456789"
	}
}
```
Compared to an older example of `libraryfolders.vdf` I found online:

```"LibraryFolders"
{
     "TimeNextStatsReport"          "XXXXXXXX"
     "ContentStatsID"		        "XXXXXXXXXXXXXXXXX"
     "1"		"D:\\SteamLibrary"
     "2"		"E:\\SteamLibrary"
     "3"		"F:\\SteamLibrary"
}
```

**Comment by EASK8ER52** [comment]
> Also experiencing this issue.
> 
> Looks like Valve have changed the format of `libraryfolders.vdf`.
> 
> 
> 
> Now, entries have a couple of fields instead of just a path.
> 
> 
> 
> ```"libraryfolders"
> 
> {
> 
> 	"contentstatsid"		"-123456789"
> 
> 	"1"
> 
> 	{
> 
> 		"path"		"F:\\Program Files (x86)\\Steam"
> 
> 		"label"		""
> 
> 		"mounted"		"1"
> 
> 		"contentid"		"123456789"
> 
> 	}
> 
> 	"2"
> 
> 	{
> 
> 		"path"		"D:\\Games\\SteamLibrary"
> 
> 		"label"		""
> 
> 		"mounted"		"1"
> 
> 		"contentid"		"123456789"
> 
> 	}
> 
> 	"3"
> 
> 	{
> 
> 		"path"		"G:\\SteamLibrary"
> 
> 		"label"		""
> 
> 		"mounted"		"1"
> 
> 		"contentid"		"123456789"
> 
> 	}
> 
> 	"4"
> 
> 	{
> 
> 		"path"		"E:\\SteamLibrary"
> 
> 		"label"		"WD Green HDD"
> 
> 		"mounted"		"1"
> 
> 		"contentid"		"123456789"
> 
> 	}
> 
> }
> 
> ```
> 
> Compared to an older example of `libraryfolders.vdf` I found online:
> 
> 
> 
> ```"LibraryFolders"
> 
> {
> 
>      "TimeNextStatsReport"          "XXXXXXXX"
> 
>      "ContentStatsID"		        "XXXXXXXXXXXXXXXXX"
> 
>      "1"		"D:\\SteamLibrary"
> 
>      "2"		"E:\\SteamLibrary"
> 
>      "3"		"F:\\SteamLibrary"
> 
> }
> 
> ```

Do you think perhaps that's the reason for it not working. And simply the plugin needs an update?

**Comment by EASK8ER52** [comment]
After some messing around I changed my LibraryFolders.vdf file to have it resemble the old version like what F15htastic posted and the plugin started working again. It seems that if you delete that file or maybe something else (who knows what) happens, then Valve will generate another LIbraryFolders.vdf and the new one will have have the info inside of it written differently than the old one. My guess is that the current Steam plugin can't read it properly and so needs to be updated to find the games.

**Comment by tfredett** [comment]
I see the problem in code now. I am not a Python dev, I will see what I can do to fix that and the associated test, as I have a feeling @EASK8ER52 and @F15htastic are correct. And it was an update to the `LibraryFolders.vdf` that is causing this. Give me a bit as I try and work on this in between my actual day job.

**Comment by tfredett** [comment]
I got it fixed from what I can tell, I am going to attach a copy of my file here, and in the meantime, I am going to work on getting a PR up for it. For folks who want a fix sooner rather than later. Make a backup of the `client.py` file in the following location. `C:\Users\Tim Fredette\AppData\Local\GOG.com\Galaxy\plugins\installed\YOUR_STEAM_FOLDER_HERE`.

After making that backup, unpack and place this client.py in that same steam folder directory as above.
[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6631919/client.zip)

**Comment by tfredett** [comment]
I got it fixed from what I can tell, I am going to attach a copy of my file here, and in the meantime, I am going to work on getting a PR up for it. For folks who want a fix sooner rather than later. Make a backup of the client.py file in the following location. C:\Users\USERNAME\AppData\Local\GOG.com\Galaxy\plugins\installed\YOUR_STEAM_FOLDER_HERE.

After making that backup, unpack and place this client.py in that same steam folder directory as above.
[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6631928/client.zip)

**Comment by tfredett** [comment]
I actually had to make some minor tweaks to my original edit. I have attached a new zip of the `client.py` containing these changes. Please use this in lieu of the zip file in my previous comment.
[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6632634/client.zip)


I have also added the code change and test update to match the new format. This can be found in the following PR.

https://github.com/FriendsOfGalaxy/galaxy-integration-steam/pull/122

Once this is merged and released, I would consider this issue closed.

**Comment by tfredett** [comment]
Also added backward compatibility for the old format, since it appears some folks may have the old format which Steam still supports. So both the new and old formats are supported. Included a new test to validate this.

**Comment by tfredett** [comment]
I now see the problem with the current fix. Working on addressing it now.

**Comment by tfredett** [comment]
Not sure what the error was found in this comment, I am guessing it was a local issue. I have since resolved it, and the code as it stands in the PR, does appear to work as expected. Please disregard the linked comment.

https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/121#issuecomment-858929684

**Comment by ferrazpedro** [comment]
> 
> 
> I actually had to make some minor tweaks to my original edit. I have attached a new zip of the `client.py` containing these changes. Please use this in lieu of the zip file in my previous comment.
> [client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6632634/client.zip)
> 
> I have also added the code change and test update to match the new format. This can be found in the following PR.
> 
> #122
> 
> Once this is merged and released, I would consider this issue closed.

Sorry for asking, but does the client.py that you linked here is the one working? Or should I get it directly from the PR? Thanks in advance!

**Comment by stankovictab** [comment]
Hi, I just want to mention that I had this exact same issue as soon as I linked up a second steam game library on my other drive - from that point on the GOG plugin didn't recognize any installed games, only showing me the owned collection. Replacing the client.py file helped this, as it now recognizes games from both libraries. Thank you @tfredett !

**Comment by tfredett** [comment]
You are welcome @stankovictab. Happy to help share the fix for this issue I am sure several others are experiencing.

**Comment by Urganot** [comment]
> From what I can tell, and I am not sure why, it appears the function `get_app_manifests` in the `client.py` file, is only loading in the app manifests from the default steam install location, and not other game install directories outside of of the default steam install location. I am not sure why, that appears to be the current issue with the code change I have though. Installed games installed in the default steam install location will show up. Any others installed in other locations, will not.
> 
> https://github.com/FriendsOfGalaxy/galaxy-integration-steam/blob/master/src/client.py#L222

Hi, I've got the same issue you discribe here. Do you have an idea what fixed it for you?

**Comment by tfredett** [comment]
Not a clue, I somehow managed to fix it, while I was messing around testing it. By the time I realized it was working again, I did not know what I changed, as from what I could tell, I changed nothing.

This issue for you @Urganot may get fixed in the next release as it looks like the PR is near completion for a release.

**Comment by FriendsOfGalaxy** [comment]
The change has been released: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/commit/4e495d1480cd48ba6e8e8f4e34e7376305c50954
Thank you all (especially @tfredett) for investigation and PR!
