### ISSUE TITLE
Steam always is offline retry

### ISSUE THREAD

**Issue by Befod** [FriendsOfGalaxy/galaxy-integration-steam#13]
`2019-10-23 21:43:41,273 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "4", "error": {"code": 101, "message": "Network error"}}`
`2019-10-23 21:44:42,481 - root - DEBUG - Sending data: {"jsonrpc": "2.0", "id": "19", "error": {"code": -32001, "message": "Method aborted"}}`

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for report. Please restart Galaxy and check with version 0.33.3. Version can be found in logs.

**Comment by Befod** [comment]
It still can't work for me. I'm sure that Steam Privacy Settings & Profile Status are set to public. 
Here is a full log file without cookies.
[log](https://github.com/Befod/zzz/blob/master/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Interesting. NetworkError is related to https://docs.aiohttp.org/en/stable/client_reference.html#aiohttp.ClientConnectionError
Don't know what is exact problem as API do not log status code.
Do you use a firewall?

**Comment by Befod** [comment]
It seems like that i can't open [steamcommunity.com](https://steamcommunity.com/) directly,how to use a SOCKS or HTTPS proxy?

**Comment by FriendsOfGalaxy** [comment]
I'm sorry, I don't now. Maybe its enough to change DNS? https://www.gog.com/forum/general/i_hate_the_galaxy_client_it_turned_my_gog_games_into_garbage/post8
Are you from China?

**Comment by xiaoas** [comment]
I encountered the exact issue days ago. However I have no idea how to attach my log file.
I use a firewall, and I'm in China, I have correct access to steam community (at least it appears so in my browser and steam client)
gog version 2.0.9.136
extension version 0.33.4
😥

**Comment by Befod** [comment]
It works with version 0.38.2 after using proxifier.Thanks.

**Comment by FriendsOfGalaxy** [comment]
@Befod thanks for update. 

For future references plugin should work if you have access to:
- steamcommunity.com 
- steam web-based chat

If you're from China you need to use proxy or VPN.
