### ISSUE TITLE
Wrong game recognized

### ISSUE THREAD

**Issue by sicu** [FriendsOfGalaxy/galaxy-integration-steam#130]
**Describe the bug**
The game 'Tetris® Effect: Connected' is wrongly recognized as a different game: 'OMEGA'
Folder: Steam\steamapps\common\Tetris Effect Connected\TetrisEffect\Binaries\Win64
File: TetrisEffect-Win64-Shipping.exe

**Comment by yessenbayev** [comment]
I can definitely prescribe to that. Seeing the same issue.

**Comment by yessenbayev** [comment]
resolved on my end

**Comment by sicu** [comment]
yeh, someone done did the fixening
