### ISSUE TITLE
Provided Steam64 ID is incorrect.

### ISSUE THREAD

**Issue by Silphatos** [FriendsOfGalaxy/galaxy-integration-steam#132]
I tried the latest integration with public profile support but it doesn't accept my Steam64 ID, what's the reason?
![image](https://user-images.githubusercontent.com/67861228/133925824-354a7850-6677-4e51-bb80-a1ae1d6b8d40.png)

**Comment by Silphatos** [comment]
My Steam profile is public but plugin says it's private, dunno why.
![image](https://user-images.githubusercontent.com/67861228/133926873-ba23adc5-ad52-4b80-bde3-893c7e7924de.png)

**Comment by FriendsOfGalaxy** [comment]
Hi, what steamID did you paste in? You can answer with an email friendsofgalaxy@gmail.com

**Comment by Silphatos** [comment]
> Hi, what steamID did you paste in? You can answer with an email [friendsofgalaxy@gmail.com](mailto:friendsofgalaxy@gmail.com)

Sent you a mail.

**Comment by FriendsOfGalaxy** [comment]
Thanks, I found a bug with regex that checks if games are available on a profile. The fix will be released soon on 1.0.1 along with better communicating of unexpected errors instead of saying that SteamId is incorrect

**Comment by FriendsOfGalaxy** [comment]
@Silphatos 1.0.1 is out. Try again and let me know if your issue is gone

**Comment by Silphatos** [comment]
Yes, it works fine now.
