### ISSUE TITLE
Diablo 2 Resurrected not populating

### ISSUE THREAD

**Issue by Kinematic9** [FriendsOfGalaxy/galaxy-integration-steam#134]
Just wanted to confirm that a newly installed copy of Diablo 2 Resurrected is not showing as an option on the GOG 2.0 installed games list.

**Comment by FriendsOfGalaxy** [comment]
shouldn't it be reported in blizzard plugin?

**Comment by Kinematic9** [comment]
Apologies, I thought this was a catch-all for gog. My mistake!
