### ISSUE TITLE
Where is the "...custom build files to the newly created folder" ?

### ISSUE THREAD

**Issue by gbr000** [FriendsOfGalaxy/galaxy-integration-steam#162]
i cannot connect to Steam through normal means aka gog.com, and the "more" page leads here which leads to:

    copy the custom build files to the newly created folder

How can I achieve that step!? And why you devs keep basics of programming such haslee and obscure way of doing things.

**Comment by Krynh** [comment]
Because those are the power user instructions. However the plugin is out of date. See here for a temp fix https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/159#issuecomment-1489195530

**Comment by gbr000** [comment]
What do you mean with that "Because those are the power user instructions". 

I know basics of programming, and how to compile a program, that doesn't make excuses "of how not give proper instructions"

every basic Linux, Windows program has instructions, that's a way you don't get lost, and know what you're doing.

Since I don't know what you're doing and I cannot know what tasks to accomplish what I am doing

**Comment by Krynh** [comment]
I have no idea either. There's a fork of the project that fixes everything https://github.com/ABaumher/galaxy-integration-steam

**Comment by gbr000** [comment]
Finally thanks!
