### ISSUE TITLE
New achievements not syncing showing on GOG

### ISSUE THREAD

**Issue by Skyryk** [FriendsOfGalaxy/galaxy-integration-steam#17]
When a game gets new achievements added they will not sync to GOG galaxy if the game has already been synced before. For example if you have a game preorderd, and the achievements are not yet revealed, then once the game is released the achievements will not show up in GOG.

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for report. For clarification:

>When a game gets new achievements added
Do you mean game has some achievements, and then developer created more achievements to unlock?

>For example if you have a game preorderd, and the achievements are not yet revealed, then once the game is released the achievements will not show up in GOG.

So if you reconnect plugin, achievements will eventually sync?
Which game for example?

**Comment by Skyryk** [comment]
I had the issue appear in both cases when a game is released and the dev adds new achievements. In the case of a game being released I had it happen with Age of Empires 2: Definitive edition. In the case of the dev adding new achievements I had it happen with Bloons TD6. I never had the new achievements sync after reconnecting the plugin. I also had no luck with the achievements syncing after reinstalling GOG galaxy.

**Comment by FriendsOfGalaxy** [comment]
I see. I'm passing this to Galaxy team, as it is not the plugin fault.

**Comment by customtemplar** [comment]
FTL has also just added achievements to the Steam version which haven't appeared in Galaxy (I have re-connected the plugin, and they've not appeared)
