### ISSUE TITLE
Missing games in steam profile

### ISSUE THREAD

**Issue by FriendsOfGalaxy** [FriendsOfGalaxy/galaxy-integration-steam#18]
Example: @Danyelalejandro has 6 SherlockHolmes games on steam (see  https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/7#issuecomment-555797072). But in his public profile there are only 3 of them: https://steamcommunity.com/profiles/76561198326486618/games/?tab=all

@Danyelalejandro
- Do you bought some of them as a pack?
- Can you log in https://steamcommunity.com/, go to https://store.steampowered.com/dynamicstore/userdata/ and paste the response you get? Those are packs and game_id's you own on steam.
- Can you just ask steam support why you don't have all your games on your public profile?

**Comment by Danyelalejandro** [comment]
@FriendsOfGalaxy 
Do you bought some of them as a pack? **Yes, I think I did**
Can you log in https://steamcommunity.com/, go to https://store.steampowered.com/dynamicstore/userdata/ and paste the response you get? Those are packs and game_id's you own on steam. **Ok, but it is huge. I will attach text and json (zipped) file**
[userdata.txt](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3872266/userdata.txt)
[userdata.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3872271/userdata.zip)
Can you just ask steam support why you don't have all your games on your public profile? **Yes, I will and let you know the answer**

**Comment by Danyelalejandro** [comment]
Hello @FriendsOfGalaxy 
Update: Today the 3 missing games have appeared in client. This is because they appeared as well in my public profile.
What happened? I still don't know. I am waiting for response from Steam...

**Comment by FriendsOfGalaxy** [comment]
Good to hear. I guess Steam has repaired.
