### ISSUE TITLE
Plugin has crashed. Retry.

### ISSUE THREAD

**Issue by skanx** [FriendsOfGalaxy/galaxy-integration-steam#19]
Hello,
Steam integration plugins keep displaying the message "Plugin has crashed. Retry" in the settings. I would say it crashes during game importation (most games seem to have been imported correctly).

It crashes a few minutes after gog galaxy launches, and when I click on retry, it crashes again a few minutes later, seemingly at the same point. Relaunching Galaxy doesn't help, neither does restarting the computer.

I found lots of game achievements import failures in the log.

plugin-team log attached:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3882807/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

Let me know if I can send more info.

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for report. This is duplication of this issue: #3 so I'm closing
