### ISSUE TITLE
No support for achievements with no name

### ISSUE THREAD

**Issue by JohnChristmann** [FriendsOfGalaxy/galaxy-integration-steam#21]
WayOut 2: Hex (appid 585950) has an achievement with no name.  Currently the plugin throws an error that an achievement name is required and will not sync this game.

**Comment by FriendsOfGalaxy** [comment]
Hi, can you show your steam public profile? We read achievements definitions from there

**Comment by JohnChristmann** [comment]
Here's my achievement page for that game: [https://steamcommunity.com/id/Soupinator/stats/585950/?tab=achievements](https://steamcommunity.com/id/Soupinator/stats/585950/?tab=achievements)

**Comment by FriendsOfGalaxy** [comment]
ok, I see. Please add one line of code after line 212 in file `backend.py`

                        name = name if name != '' else ' '

and check if it works for you.

**Comment by JohnChristmann** [comment]
I'm unsure about how to go about this.  Galaxy appears to store the plugin as a single .db archive and I have no clue how to open it.

**Comment by FriendsOfGalaxy** [comment]
Plugins are kept here on windows: 
C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed

And here on mac: 
~/Library/Application\ Support/GOG.COM/Galaxy/plugins/installed

there should be loose .py files in coresponding folders

**Comment by JohnChristmann** [comment]
Well the plugin is crashing on load with that change.  Must be a syntax error, though I'm not too familiar with Python.

**Comment by GauthierPLM** [comment]
@JohnChristmann repalce the parse function with the following code:
(To do so, go in the steam folder located in `C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\` open `backend.py`. Go line 199 and replace the lines 199 to 213 (the whole function). After this, restart galaxy and test).

```
        def parse(text):
            html = HTML(html=text)
            rows = html.find(".achieveRow")
            achievements = []
            try:
                for row in rows:
                    unlock_time = row.find(".achieveUnlockTime", first=True)
                    if unlock_time is None:
                        continue
                    unlock_time = int(self.parse_date(unlock_time.text).timestamp())
                    name = row.find("h3", first=True).text
                    name = name if name != '' else ' '
                    achievements.append((unlock_time, name))
            except (AttributeError, ValueError, TypeError):
                logging.exception("Can not parse backend response")
                raise UnknownBackendResponse()
```

I was just passing by and wanted to give some help. Hope it is useful.

**Comment by JohnChristmann** [comment]
Ok the location of the code makes more sense in that snippet (that's after line 209, rather than 212 as originally suggested.)  It was still causing the plugin to crash on load, but after quite a bit of tinkering I figured out it's because my text editor is using tabs for indentation, and the original code is using spaces...Python can really be a pain sometimes.

This change did allow the game to sync properly though, thank you two.
