### ISSUE TITLE
Support sharedconfigs with UserLocalConfigStore

### ISSUE THREAD

**Issue by metrip** [FriendsOfGalaxy/galaxy-integration-steam#22]
I'm assuming `get_game_library_settings_file` etc. are preparing for syncing user category information in the near future.

Code in https://github.com/FriendsOfGalaxy/galaxy-integration-steam/blob/master/src/backend.py#L264 reads `sharedconfig.vdf` app data from `UserRoamingConfigStore` but sharedconfig data can also be saved in a `UserLocalConfigStore` struct. 

Example (snippet):

```
"UserLocalConfigStore"
{
	"Software"
	{
		"Valve"
		{
			"Steam"
			{
				"SSAVersion"		"3"
				"PrivacyPolicyVersion"		"2"
				"DesktopShortcutCheck"		"0"
				"StartMenuShortcutCheck"		"1"
				"AutoLaunchGameListCheck"		"1"
				"apps"
				{
					"211420"
					{
						"LastPlayed"		"1361120949"
						"cloudenabled"		"1"
						"tags"
						{
							"0"		"Done"
						}
					}
...
```

Also, please note the fully lowercase `apps` key -- linked line of code uses ucfirst `Apps`.

**Comment by FriendsOfGalaxy** [comment]
@metrip  Tags import functionality is already present both in plugin and galaxy client, 
Settings -> Features 
![image](https://user-images.githubusercontent.com/48480506/69711679-c1115700-1101-11ea-84d3-74f80e64147a.png)

**Comment by metrip** [comment]
Thanks! The Galaxy UI did not update the metadata until a restart so I got confused.

Closing.
