### ISSUE TITLE
Add support for localization in rich presence.

### ISSUE THREAD

**Issue by SinZ163** [FriendsOfGalaxy/galaxy-integration-steam#24]
Since the new Steam Chat launched, Valve added support for localization in rich presence.

A textbook example is Dota, where it will say `Ranked: Lvl 15 Underlord` for example, but this integration will show it as `#DOTA_RP_PLAYING_AS` without showing that param0 is `#dota_lobby_type_name_ranked`, param1 is `15` and param2 is `#npc_dota_hero_abyssal_underlord`.

For this example, the definition for `#dota_rp_playing_as` is `{%param0%}: Lvl %param1% {%param2%}` where {%paramX%} tells you to take the param, and then look up the localization string for that value, while others like %paramY% are literal values.

This is all defined in the app in steam, and is visualized quite nicely on [steamdb](https://steamdb.info/app/570/localization/)

**Comment by FriendsOfGalaxy** [comment]
Was fixed in https://github.com/FriendsOfGalaxy/galaxy-integration-steam/commit/6d7fb6f8fb08aab42882657688e0c64d23fad28d
