### ISSUE TITLE
Installed Games are not shown

### ISSUE THREAD

**Issue by Chiaray** [FriendsOfGalaxy/galaxy-integration-steam#25]
**Describe the bug**
First of all: Sry for my english. 
My installed Steam Games are not shown in the Installed section of the GOG Galaxy 2.0 launcher. Only if i install the games on my System drive C, they are shown in the installed section. 

**To Reproduce**
I don't know how u can reproduce it.

**Expected behavior**
The plugin need to detect games from Steam even if they are not on the drive C installed

**Comment by FriendsOfGalaxy** [comment]
Hey, this works for me. Please attach logs file - we'll investigate your case.

**Comment by Chiaray** [comment]
This is the log file of the plugin i think: 
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3973633/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

And this of the GOG Client
[GalaxyClientService.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3973636/GalaxyClientService.log)

**Comment by FriendsOfGalaxy** [comment]
The plugin doesn't find custom locations. Those should be written in:

`C:\Program Files (x86)\Steam\steamapps\libraryfolders.vdf` (assuming you have steam installed on C)

Could you upload this file?

**Comment by Chiaray** [comment]
Oh ok. Yeah i upload this file. 
here it it: 

[libraryfolders.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3973749/libraryfolders.zip)

**Comment by FriendsOfGalaxy** [comment]
Hmm everything is OK there. We know about installed games from the list of appmanifests (`.acf`) files.
Those detected in your both steam locations are:
```
['c:/program files (x86)/steam\\steamapps', 'E:\\Games [Steam]\\steamapps']
c:/program files (x86)/steam\steamapps\appmanifest_228980.acf
c:/program files (x86)/steam\steamapps\appmanifest_326460.acf
```
Nothing found on disk E. Do you have any appmanifest in 'E:\\Games [Steam]\\steamapps' ?

**Comment by Chiaray** [comment]
Here [E:\Games [Steam]\steamapps] are 13 appmanifest files.

**Comment by FriendsOfGalaxy** [comment]
ok... please unpack this zip to
`C:\Users\mesco\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8` replacing `client.py` file

[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3973947/client.zip)

I've added more logging for this as looks like strange bug. Then restart Galaxy and reupload plugin log

**Comment by Chiaray** [comment]
So i've  unpacked this zip and restartet Galaxy but still no installed games. here is the log:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3973987/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3974154/client.zip)

This should work. The problem was in not escaped square brackets in your path name. Please check.

**Comment by Chiaray** [comment]
i replaced it here: (C:\Users\Jan\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8) and atm it doen't work... 

here's the log file:
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3974185/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
I'm sorry, too quick. This time tested:

[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3974230/client.zip)

**Comment by Chiaray** [comment]
No problem :)
Now it works!! Thanks!! :D

**Comment by FriendsOfGalaxy** [comment]
I'm glad to help :) 

Fix will be deployed in next steam plugin version
