### ISSUE TITLE
Cannot import achievements of TF2

### ISSUE THREAD

**Issue by deluxghost** [FriendsOfGalaxy/galaxy-integration-steam#30]
**Describe the bug**

This plugin doesn't support TF2 (`appid: 440`) achievement import.

The reason is the achievements page has a different (old) layout:
check this out: https://steamcommunity.com/my/stats/TF2?tab=achievements&l=english

There is no `achieveRow` class and the HTML structure is slightly different, thus no achievement parsed.

Related code:

https://github.com/FriendsOfGalaxy/galaxy-integration-steam/blob/64db723923b01b9cc770b74ac5677baea70256f2/src/backend.py#L223-L240

**Expected behavior**

Support TF2 (and any other games have the same issue if there are) achievements import.

**Comment by FriendsOfGalaxy** [comment]
Hey, thanks for details description!

We're currently moving out from html parsing in favor of protobuf methods (used by Steam Client), so hopefully this won't be problem soon :)

**Comment by Danyelalejandro** [comment]
This would help my issue too? [https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/26](url)

**Comment by Tauron93** [comment]
@FriendsOfGalaxy any idea when the the plugin will be updated to use protobuf? Because I am having a lot of trouble with Steam achievements recently...

**Comment by Danyelalejandro** [comment]
For me it has been a real nightmare. It has damaged all my experience with the client. I am waiting as well this to be corrected

**Comment by FriendsOfGalaxy** [comment]
Getting achievements from protobufs was already done.

> I am having a lot of trouble with Steam achievements recently..
Probably related to this: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/26
