### ISSUE TITLE
Family View results in Steam failing to connect

### ISSUE THREAD

**Issue by doulweapons** [FriendsOfGalaxy/galaxy-integration-steam#31]
If you use Family View, you can't connect it to the Steam Galaxy integration

**To Reproduce**
1. Set up Family View (https://support.steampowered.com/kb_article.php?ref=5149-EOPC-9918#setitup) 
2. Open Galaxy 2.0 and try to set up the Steam Integration.
3. The connection fails

Note: If you already have the Steam connection set up, it will disconnect the next time you open Galaxy.

I don't know if there's any way around this, it might be working as intended from Steam's side.
There is a pin associated with Family View, but it doesn't help with the connection.

**Comment by FriendsOfGalaxy** [comment]
@doulweapons  

does this still occur ? 
can you please provide your logs from C:\ProgramData\GOG.com\Galaxy\logs folder here or on my mail friendsofgalaxy@gmail.com

**Comment by doulweapons** [comment]
Looks like it is fixed, awesome!
