### ISSUE TITLE
Last Played Time Not Updating/Imports as None

### ISSUE THREAD

**Issue by rowanm127** [FriendsOfGalaxy/galaxy-integration-steam#32]
Last played time for Steam games is not being updated or imported properly. Logs show all last_played_time for imported games as being 'None' even though the game has been played or started recently.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4097304/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
New release is uploaded. Now, it should work as expected. Feel free to reopen if something goes wrong.
