### ISSUE TITLE
Failed to import library

### ISSUE THREAD

**Issue by artemy-osipov** [FriendsOfGalaxy/galaxy-integration-steam#33]
**Describe the bug**
Once the integration is connected, the Steam library remains empty.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Connect integration (gog 2.0.12 beta)
2. Log in with steam account
3. Wait 2 minutes
4. Press Sync integrations
5. Wait few minutes

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.txt](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4097753/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.txt)

**Comment by FriendsOfGalaxy** [comment]
Thanks for report. We're working on it.
