### ISSUE TITLE
Cannot connect Steam and Uplay 平台连接无法连接Steam和Uplay

### ISSUE THREAD

**Issue by LucherChu** [FriendsOfGalaxy/galaxy-integration-steam#34]
![TIM截图20200122122304](https://user-images.githubusercontent.com/60191014/72915115-c0e8ad00-3d7a-11ea-99db-34e9a843c9af.png)
It always tell me it cannot open and I need to try again, but when I press the button it happens nothing. And it isn't solved even I use a VPN. I'm in China. 
当我连接Steam和Uplay时，提示无法启动，但重试按钮点了以后也没有任何反应。我在中国，就算我用VPN也是一样的问题。

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for report.
Please, attach log files https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files 
This will help in further investigation

**Comment by LucherChu** [comment]
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4102914/logs.zip)
Attaached

**Comment by wordlesswind** [comment]
@FriendsOfGalaxy 
In Mainland China, we do not have direct access to steamcommunity.com .
It's blocked.
So we usually use a proxy tool to access it.
But it seems that Galaxy does not detect Internet Explorer Proxy Settings. So that it is not possible to access steamcommunity.com through a proxy server.
Common proxy tools: [shadowsocks-windows](https://github.com/shadowsocks/shadowsocks-windows), [v2ray](https://github.com/v2ray/v2ray-core), [trojan](https://github.com/trojan-gfw/trojan), etc.

**Comment by FriendsOfGalaxy** [comment]
Thanks, we are working on alternative login solution that now use steamcommunity.com. Please, be patient

**Comment by wordlesswind** [comment]
OK, thank you for all this!
I don't know the difficulty of alternative login solution, but I decided to give a suggestion.
If the alternative is difficult to accomplish, just let galaxy and the plugin detect the system proxy settings.
![ie_proxy_settings](https://user-images.githubusercontent.com/9050713/73536116-367e0880-4460-11ea-98c3-6fddc1c2498a.PNG)
Proxy tools usually use [MaxMind GeoLite2](https://dev.maxmind.com/geoip/geoip2/geolite2/) and [GFWList](https://github.com/gfwlist/gfwlist) to route different traffic.
Therefore, it only needs to be set through the system proxy.
The alternative login solution should only be completed after the release of Steam China.
It's impossible to bypass steamcommunity.com to get friend status.
Finally, you can test whether the site has been blocked in Mainland China by [GreatFire.org](https://en.greatfire.org/analyzer)

**Comment by FriendsOfGalaxy** [comment]
@wordlesswind  @LucherChu 

new authentication flow should handle logging from China. Please try this pre-release
https://github.com/FriendsOfGalaxy/galaxy-integration-steam/releases/tag/0.46.9

**Comment by wordlesswind** [comment]
> @wordlesswind @LucherChu
> 
> new authentication flow should handle logging from China. Please try this pre-release
> https://github.com/FriendsOfGalaxy/galaxy-integration-steam/releases/tag/0.46.9

This is great news and I am using it.
No issues were found at this time.
Thank you!

**Comment by wordlesswind** [comment]
@LucherChu

Uplay 的问题是因为 GALAXY 并不支持系统代理设置，所以实际上你是直连 Uplay 的服务器。

而 connect.ubisoft.com 至今只指向 Ubisoft 的加拿大服务器，连接超时是正常的。

**Comment by LucherChu** [comment]
> @wordlesswind @LucherChu
> 
> new authentication flow should handle logging from China. Please try this pre-release
> https://github.com/FriendsOfGalaxy/galaxy-integration-steam/releases/tag/0.46.9

Using it, and it works perfectly. Thanks for your efforts on this issue.

**Comment by LucherChu** [comment]
> @LucherChu
> 
> Uplay 的问题是因为 GALAXY 并不支持系统代理设置，所以实际上你是直连 Uplay 的服务器。
> 
> 而 connect.ubisoft.com 至今只指向 Ubisoft 的加拿大服务器，连接超时是正常的。

这就很奇怪了，我现在使用的电信是可以裸连Uplay，打开网页版的Ubisoft Club的（然后在我打这行字的时候Uplay的连接界面弹出来了，真就是看人品）。
所以GOG的平台连接难不成是通过Github下载所需文件（众所周知的原因，国内Github下载很慢甚至无法下载）并且限制了一定时间内连接不上就提示失败吗。。。

**Comment by FriendsOfGalaxy** [comment]
In case the uplay issue is still occuring, please report it on uplay github issues page. 
https://github.com/FriendsOfGalaxy/galaxy-integration-uplay
