### ISSUE TITLE
Unlocked achievements don't show up because of trailing whitespace

### ISSUE THREAD

**Issue by BenediktConze** [FriendsOfGalaxy/galaxy-integration-steam#36]
**Describe the bug**
On some games, some (but not always all) achievements that are unlocked in Steam are not unlocked in Galaxy.
For me, affected games are "Tomb Raider (2013)" (0/31 unlocked achievements unlocked in Galaxy) and "Super Meat Boy" (1/13 unlocked achievements unlocked in Galaxy). However, the achievements seem to work for other people for these games.
This seems to be caused by a trailing whitespace in the achievement_name. For example, an excerpt from the log with the achievements of "Super Meat Boy":

`2020-02-21 20:03:01,424 - plugin - INFO - Asked for achievs for 40800`
`2020-02-21 20:03:01,424 - galaxy.api.jsonrpc - INFO - Sending notification: method=game_achievements_import_success, params={'game_id': '40800', 'unlocked_achievements': [Achievement(unlock_time=1531695305, achievement_id=None, achievement_name='Wood Boy '), Achievement(unlock_time=1508856734, achievement_id=None, achievement_name='Nostalgia '), Achievement(unlock_time=1515471600, achievement_id=None, achievement_name='Living In the Past '), Achievement(unlock_time=1582245031, achievement_id=None, achievement_name='Old School '), Achievement(unlock_time=1540519098, achievement_id=None, achievement_name='The End '), Achievement(unlock_time=1508856734, achievement_id=None, achievement_name='I Have Crabs! '), Achievement(unlock_time=1542938117, achievement_id=None, achievement_name='Metal Head '), Achievement(unlock_time=1582249594, achievement_id=None, achievement_name='I Smell something Fishy... '), Achievement(unlock_time=1508856734, achievement_id=None, achievement_name='The Commander '), Achievement(unlock_time=1508856734, achievement_id=None, achievement_name='The Bootlicker '), Achievement(unlock_time=1582245032, achievement_id=None, achievement_name='The Jump man '), Achievement(unlock_time=1582245713, achievement_id=None, achievement_name='The Fly guy '), Achievement(unlock_time=1582250059, achievement_id=None, achievement_name='Well look at you!')]}`

Notice the trailing whitespace in every achievement_name except `Well look at you!`. `Well look at you!` is also the only achievement in "Super Meat Boy" that shows up as unlocked in Galaxy.

**To Reproduce**
Unknown. Syncing or reinstalling the integration does not change anything.

**Expected behavior**
Every achievement that is unlocked in Steam should also be unlocked in Galaxy.

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4237650/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
@BenediktConze  should be fixed in  v0.46.5 please confirm

**Comment by BenediktConze** [comment]
This fixed my problem, thanks. Although I guess it breaks achievements with spaces at the front/back if those exist

**Comment by FriendsOfGalaxy** [comment]
No, this should work properly with Galaxy backend, confirmed with the GOG that their achievement definitions should not have trailing spaces.

Thanks for help with this bug!
