### ISSUE TITLE
New Authentication Flow was working. Now: "Steam Offline Retry."

### ISSUE THREAD

**Issue by theunusualsuspect** [FriendsOfGalaxy/galaxy-integration-steam#37]
I followed the instructions here: https://www.reddit.com/r/gog/comments/faao1s/test_of_the_new_authentication_flow_in_steam/ - on the day it was posted.

It worked fine for a few days, but now I get the following:

![steam-offline-retry](https://user-images.githubusercontent.com/45131932/75815601-9d5a4e80-5d8b-11ea-80dd-5ee4c3823d3e.PNG)

Clicking **Retry** does nothing - no response at all, no error, literally no changes to what's shown in the screenshot above (same with Origin).

I restarted Galaxy and saw this for a few seconds:

![steam-offline-retry-2](https://user-images.githubusercontent.com/45131932/75816080-6c2e4e00-5d8c-11ea-90ac-4618445b25b6.PNG)

Then it was back to the first screenshot.

I disconnected and reconnected the Steam integration, entered my username, password and Steam Guard code again and this fixed the issue.

**Comment by FriendsOfGalaxy** [comment]
Hey, it seems like steam services were down at midnight (https://steamstat.us). Plugin shouldnt go into offline mode but crash instead, will work on that. Thanks!
