### ISSUE TITLE
"Plugin has crashed. Retry" on first attempt of connecting.

### ISSUE THREAD

**Issue by pivotiiii** [FriendsOfGalaxy/galaxy-integration-steam#4]
The plugin crashes upon trying to connect GLX2 with Steam. After clicking the connect button, the plugin takes a couple of seconds to crash. It never shows the available features or a login form. I attached the log file of one such attempt. This was done with administrator priviliges after a reboot.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/3489423/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Thank you for the report. The plugin has problems with reading some of your `.acf` files:
* `S:\Steam\steamapps\appmanifest_17080.acf`
* `S:\Steam\steamapps\appmanifest_229870.acf`
* `S:\Steam\steamapps\appmanifest_232910.acf`
* `S:\Steam\steamapps\appmanifest_233050.acf`
* `S:\Steam\steamapps\appmanifest_233070.acf`
* `Y:\Steam\steamapps\appmanifest_17080.acf`
* `Y:\Steam\steamapps\appmanifest_229870.acf`
* `Y:\Steam\steamapps\appmanifest_232910.acf`
* `Y:\Steam\steamapps\appmanifest_233050.acf`
* `Y:\Steam\steamapps\appmanifest_233070.acf`

Would it be possible to attach those files to the issue?

**Comment by pivotiiii** [comment]
I had a look at these files and they are all empty. The app ids seem to belong to some deleted demos /f2p games I have tried in the past.

**Comment by FriendsOfGalaxy** [comment]
New version of the plugin (https://github.com/FriendsOfGalaxy/galaxy-integration-steam/releases/tag/v0.31) should correctly handle empty/damaged .acf files.
