### ISSUE TITLE
Cannot read or import achievements from specific games

### ISSUE THREAD

**Issue by jdetraz** [FriendsOfGalaxy/galaxy-integration-steam#40]
**Bug**

I noticed that the Steam plugin does not read and import the achievements from a few specific games, like 'Ori and The Will of the Wisps' or 'Red Dead Redemption 2'. The progress tab of those games in GOG 2.0 displays 'NA' instead of the achievements listing.

Disconnecting and reconnecting the plugin does not fix the issue.

**Games (non exhaustive listing)**

Red Dead Redemption 2
~~Ori and The Will of the Wisps~~

**Comment by FriendsOfGalaxy** [comment]
Hi, please attach logs: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files
after restarting Galaxy (when "importing" snackbar will rich 100%)

**Comment by jdetraz** [comment]
Hi, 
Please find below the requested file.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4340333/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by jdetraz** [comment]
Update: Ori and The Will of the Wisps tracking is now working. It took a few days.

I wonder if RDR2 Steam is not tracking progress because it works via the Rockstart game launcher too?

**Comment by FriendsOfGalaxy** [comment]
Hi, thanks for logs. From what is there I see that plugins sends achievements correctly.

So looks like Galaxy issue. Looks the same as this: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/17
