### ISSUE TITLE
Crash on startup after PC Restart

### ISSUE THREAD

**Issue by SonOfDiablo** [FriendsOfGalaxy/galaxy-integration-steam#41]
**Describe the bug**
(Might be related to https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/39)

When starting GoG Galaxy 2.0 after having restarted my computer, the Steam Integration reports as being "Crashed".
However it runs just fine if I click "retry" for the integration and when I restart GoG Galaxy 2.0.

**Expected behavior**
The Integration would start and run without crashing.

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4375392/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Hi @SonOfDiablo I'm sorry for late response.

Does it still occur for you? There were a few releases since your report

**Comment by SonOfDiablo** [comment]
I haven't noticed it for a while, so I guess the issue has been resolved yes.

Thank you!
