### ISSUE TITLE
Steam Plugin 0.49 crashing 

### ISSUE THREAD

**Issue by Demitrix2k** [FriendsOfGalaxy/galaxy-integration-steam#43]
Been crashing every time i launch a game pretty much the past few days, here's the logs.
[GalaxyClient.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4425954/GalaxyClient.log)

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4425938/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
I dont see any crash near launching the game but a bit futher it shows 
```
  File "C:\Users\username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8\protocol\websocket_client.py", line 190, in _authenticate
    return await self._protocol_client.authenticate_web_auth(steam_id, miniprofile_id, account_name, token, auth_lost_handler)
AttributeError: 'NoneType' object has no attribute 'authenticate_web_auth'
```
which seems like an issue which could cause a crash.

@Demitrix2k 
Can i ask you to disconnect the plugin, close Galaxy client, delete the plugin from your C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed and launch Galaxy client and connect to the steam plugin again? 

It seems like a lot of steps but this will ensure that the plugin files did not corrupt during galaxy update (sometimes it seems like galaxy can only partially download a new version which breaks some files) and the disconnect/connect proceedure should put you through a different authentication flow cause from what i see in your logs it was using a backwards compatibility solution for older versions of the plugin.

**Comment by Demitrix2k** [comment]
Same result, i am leaning towards this being an issue that relates to a game i recently acquired, Bannerlord II.
https://store.steampowered.com/app/261550/Mount__Blade_II_Bannerlord/
Its registering every game except for Bannerlord II, and when i re-imported my games i have no tracked gametime registered to it, and the plugin seems to crash every time it tries to sync.
[GalaxyClientService.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4427726/GalaxyClientService.log)
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4427727/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Okay i see it seems to drop the connection mid-user presence import, there is a potential fix for this coming in the next update. 

If you want to try out if the fix works for you, close galaxy, delete steam plugin from C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed directory and unzip this new version instead 
[steam_windows.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4427898/steam_windows.zip)

fingers crossed it works, if not i will investigate the issue further, Thanks!

**Comment by Demitrix2k** [comment]
That early .50 version isn't perfect but its practical since it makes it possible to actually run steam games which is what mattered the most, thank you.
In terms of what works and what doesn't, it only seems to import gametime and not achievements, and it only happens on the game you launch, it does not import gametime and achievements on games from Steam in general.
It also say's that its offline from Steam, but its not.
video demo
https://streamable.com/g7w99m
Thank you for the fast response considering the circumstances, stay safe and healthy.
