### ISSUE TITLE
Games missing, custom grids removed, tags removed

### ISSUE THREAD

**Issue by BluePlasticCup** [FriendsOfGalaxy/galaxy-integration-steam#44]
**Describe the bug**
Some games are missing. Custom grids from most Steam games have been removed. Other integrations seem fine. 189 games that were once sorted are now missing all their tags. Importing tags from Steam does nothing.

**To Reproduce**
1. Open Galaxy 2.0 on account with ~2k games.
2. Wait a few minutes and look.

**Expected behavior**
Integration should be showing all my games.
All tags should be as I left them or at least reapplied when importing tags from Steam.
Custom grids (art) should still be applied.

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4463741/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Hello BluePlasticCup, 

can you please provide rest of your steam logs as it seems only the newest created one is attached which doesnt have any calls to owned games or tags in it.
Please send me all the  
plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log
plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.1
plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.2 
files you have in your C:\ProgramData\GOG.com\Galaxy\logs folder here or on email friendsofgalaxy@gmail.com so i can investigate this further.

**Comment by BluePlasticCup** [comment]
My bad. Thought I added all of them.

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4483334/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log.zip)

**Comment by FriendsOfGalaxy** [comment]
I can see that tags are properly sent from the plugin to galaxy. It seems that the issue is on galaxy client side, unfortunately i can't do anything about that, try creating a bug report with those logs (and probably galaxy client logs ) here https://mantis2.gog.com/bug_report_page.php so that gog people can see it.
