### ISSUE TITLE
Plugin not recognizing installed titles

### ISSUE THREAD

**Issue by QuietusWolfe** [FriendsOfGalaxy/galaxy-integration-steam#48]
Steam plugin is connected and shows my library, but none of my installed Steam games show as installed.

Have tried DCing the plugin and restarting the client, which didn't fix the issue.

Log files: https://drive.google.com/drive/folders/1d0wpv4ZNHr5qNwRTJWSlystxJkWR9n7h?usp=sharing

**Comment by FriendsOfGalaxy** [comment]
Hello, 

I will be investigating your issue right now, can you tell me whether you have House Flipper installed and whether this path exists on your pc
"E:\\House Flipper On the Moon\\Steam\\steamapps\\libraryfolders.vdf" ?

**Comment by QuietusWolfe** [comment]
House Flippers is installed, but it's not a legit copy (you can yell at me for piracy later, but I do plan on buying it).

As for the folder paths, none of them are present.

**Comment by AmitKhare1088** [comment]
Hello FriendsOfGalaxy,

Thank you for your work on this integration.

I want to report similar issues, but the titles in question are legit.

1)  Nino Kuni 2 is not appearing in the installed category despite being installed.

D:\\Steam\steamapps\common\Ni no Kuni II Revenant Kingdom does exist.
Also steam path is there in the registry editor.

2) The elder scrolls V special edition is not appearing is GOG steam section, despite being available in steam. It is not installed yet, but not showing up.

**Comment by FriendsOfGalaxy** [comment]
@QuietusWolfe I see. But have you changed something in Steam to making it work for you? Or have you used any 3-rd party script? I'm asking because `Computer\HKEY_CURRENT_USER\Software\Valve\Steam`->`SteamPath` refers to your default Steam path. It usually should be something like `c:/program files (x86)/steam`. We inspect `libraryfolders.vdf` file 

Hello @AmitKhare1088 
ad 1. provide logs please - may be helpful for this issue!
ad 2. follow this wiki: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Common-problems :)

**Comment by QuietusWolfe** [comment]
Ok, I was looking for SteamPath as a separate folder, so my mistake there. As an entry, it does exist and is listed as E:\Steam, which is where I have Steam installed.

As for House Flippers, it's a modified .INI file specific to the game in question that tricks the game itself. It doesn't effect Steam directly(as far as I know).

**Comment by AmitKhare1088** [comment]
I tried to find logs folder - But I don't see it. As per the Wiki, I am suppose to find it in -
C:\ProgramData\GOG.com\Galaxy\logs
But it's not there :(

**Comment by FriendsOfGalaxy** [comment]
@AmitKhare1088  

Do you have a ProgramData folder on other drives? (for example D:\ E:\) Can you see if that folder exists on any of them?

**Comment by FriendsOfGalaxy** [comment]
@QuietusWolfe 
so do you claim that `Computer\HKEY_CURRENT_USER\Software\Valve\Steam\SteamPath` is `E:\Steam`, right? The logs tells something else, that is strange...

Place use this:
[client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4521143/client.zip)
- close Galaxy
- open file explorer, paste `%LocalAppData%\GOG.com\Galaxy\plugins\installed` in navigation top bar
- open `steam_ca27391f-2675-49b1-92c0-896d43afa4f8`
- unpack this zip. `client.py` file should be replaced
- launch Galaxy
- check if works
- upload logs please even if now works

**Comment by QuietusWolfe** [comment]
Ok, that file fixed it. My installed games are showing up again.

https://drive.google.com/drive/folders/1am8pNSaoXyha85vkqR8conyqnzGSbQoj?usp=sharing

**Comment by AmitKhare1088** [comment]
Hello @FriendsOfGalaxy , 

Thank you for the log tip, it worked. I do have games in all my drives - C, D & E. But apart from the missing ones, the other installed games in those drives are showing up. I have attached the log file.
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4522970/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
@QuietusWolfe 
I have no idea why it now works for you. Previous version will work as well, as you registry shows now proper value: `E:\Steam`.

@AmitKhare1088 
please attach more logs. They are rolling quickly and this one have no sufficient information.
You can zip all `log.1`, `log.2` ect files and attach here

**Comment by AmitKhare1088** [comment]
Hello @FriendsOfGalaxy ,

I zipped all the log files in the folder, please take a look.

Thank you :)

[Logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4529273/Logs.zip)

**Comment by FriendsOfGalaxy** [comment]
@AmitKhare1088 
do you mean this game?
https://steamdb.info/app/798460/

From the logs I see the plugin sends it as installed. Can you show printscreen from Galaxy? If stil does not appear, please paste also `GalaxyClient.log` up to `GalaxyCLient.log.6`

As far as The elder scrolls V is concerned, please follow separate issue #55

**Comment by AmitKhare1088** [comment]
@FriendsOfGalaxy  

There was an update to GOG Galaxy today. It fixed both of my reported issues.
No idea how, but it did. if you need any logs from me, please let me know.

Thank you.

**Comment by FriendsOfGalaxy** [comment]
Ok, so closing without any resolution in the code, as the issues has gone
