### ISSUE TITLE
Standalone Mods like Enderal not listed

### ISSUE THREAD

**Issue by Lahiri** [FriendsOfGalaxy/galaxy-integration-steam#5]
Hello, 
stand-alone mods like Enderal (link: https://store.steampowered.com/app/933480/Enderal_Forgotten_Stories/) are not visualized in the library.
That's fine when not installed, but at least when it is installed it would be nice to be able to launch it from GOG Galaxy.

**Comment by FriendsOfGalaxy** [comment]
This is something on the GLX side. Please contact GOG about that (cogwheel menu, Report Issue)
