### ISSUE TITLE
Steam plugin crash

### ISSUE THREAD

**Issue by Juliotenorio** [FriendsOfGalaxy/galaxy-integration-steam#51]
I think I have this problem since last month or a little more, I open GOG the games and friends are loaded, and in lass than a minute the plugin crash, I press to retry and works, but again in less a one minute crash. 

[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4533487/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
[GalaxyClientService.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4533488/GalaxyClientService.log)

**Comment by FriendsOfGalaxy** [comment]
Hey @Juliotenorio 

its hard to deduce what is the cause of the issue from these logs alone, can you send the rest of the plugin-steam logs? (log, log.1, log.2 etc) Along with GalaxyClient.log(s) so i can see what it wants from the plugin. 

You can send it here or on my email friendsofgalaxy@gmail.com 

Thanks!

**Comment by Juliotenorio** [comment]
I sent for your email. Hope I sent everything, if miss something just ask.

Thanks!

**Comment by K0bin** [comment]
Still crashing for me too.
[Logs](https://gist.github.com/K0bin/fa6783aefb4e45515dddc4057a9ebeaa)

**Comment by Juliotenorio** [comment]
Since version 0.50.8 the crash has fixed. 

Thanks!

**Comment by K0bin** [comment]
Still crashing for me.
