### ISSUE TITLE
Games that were once family shared before buying don't appear

### ISSUE THREAD

**Issue by TM-CG** [FriendsOfGalaxy/galaxy-integration-steam#53]
**Before start**
- check if your issue is known: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Common-problems

**Describe the bug**
All the games that I tried with family sharing before buying don't appear. 
Basically I played the games before with family sharing, and bought them sometime after. These games are not imported to GOG

In my case those games are Dark Souls III and F1 2019.

When I revert to an older version 0.45 it works

**Expected behavior**
All owned games should be imported.

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4535490/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Hi @TM-CG ,

thanks for the report and the specific repro steps, i will try to repeat the situation on my side and investigate the issue.

**Comment by TM-CG** [comment]
Hi,
just noticed now (and I don't know if it is the intended behavior) that older versions (0.45) can import family shared games that you don't own as well. Which doesn't happen in 0.52...

Hope it helps, thank you for your work.

**Comment by FriendsOfGalaxy** [comment]
Hi @TM-CG  can you see if this version will work for you?

[steam_sharing_investigation.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4551645/steam_sharing_investigation.zip)


To install it
1 Close Galaxy Client
2 Delete the contents of C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8 directory
3 Unpack the provided zip file in the C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8 directory
4 Run Galaxy Client.

In case it still doesn't work, please send your logs here or attached to mail on friendsofgalaxy@gmail.com.

Thanks!

**Comment by TM-CG** [comment]
Hi @FriendsOfGalaxy, it gives me the same thing, but I noticed that if I enable the new GoG feature to show "Subscriptions" it shows those games under the Subscription tab marked as family share (altough I bought them after trying them through Family Share).

Here are the logs
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4552318/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
@TM-CG  Thanks for the logs, they given me much insight into the problem.

I think the new version will have it fixed, you can check it out if you have the time. (install procedure should be the same as before)
[steam_fs_fix.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4557632/steam_fs_fix.zip)

If it works i will probably make a new release of the plugin on monday.

**Comment by TM-CG** [comment]
Hey @FriendsOfGalaxy, the new version works! Had to reimport everything again after the procedure but now the games show up on the Owned tab.

Thank you!

**Comment by FriendsOfGalaxy** [comment]
Thanks for the update! Glad its working now!

**Comment by Hamtarotaro** [comment]
I installed the steam_fs_fix in the "C:\Users\Username\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_ca27391f-2675-49b1-92c0-896d43afa4f8" direcctory and now i can see the games in the "owned" category but they are still tagged as "shared". 
At least i can see them all in the same place but still confusing.
Do i have to delete the directory before installing the fix?

**Comment by TM-CG** [comment]
I went to Feature settings and reimported all the steam information and it fixed that problem

**Comment by Hamtarotaro** [comment]
Sorry, i tried that and deleting the steam plugin folder and replacing everything with the fix and still no change .

**Comment by Hamtarotaro** [comment]
[GalaxyClient.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4560800/GalaxyClient.zip)
Here is the log.

**Comment by Hamtarotaro** [comment]
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4560802/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.zip)
Sorry wrong one.

**Comment by FriendsOfGalaxy** [comment]
@Hamtarotaro 
If a game is coming from both owned games and family sharing we will send it once as an owned game and once as part of family sharing subscription.

As long as all the proper games are shown in the owned games tab for the appropriate platform 
![image](https://user-images.githubusercontent.com/48480506/80949428-4d801e00-8df4-11ea-8c42-22196989e4e7.png)
its all i can do.

If they have a subscription tag then its something on the Galaxy Client side, plugins job is to provide as accurate data as possible.
