### ISSUE TITLE
Authentication expires silently

### ISSUE THREAD

**Issue by mwisnicki** [FriendsOfGalaxy/galaxy-integration-steam#54]
Authentication expires pretty often as per #27 and there's no sign of it except missing games and "disconnected" status in options. It would be great if GoG could display some sort of a message or generate notification.

**Comment by FriendsOfGalaxy** [comment]
Hi @mwisnicki 

please send me your logs from C:\ProgramData\GOG.com\Galaxy\logs
here or on my email friendsofgalaxy@gmail.com

**Comment by FriendsOfGalaxy** [comment]
closed due to lack of activity
