### ISSUE TITLE
Steam achievements do not sync (always 0%)

### ISSUE THREAD

**Issue by Tauron93** [FriendsOfGalaxy/galaxy-integration-steam#56]
Steam achievements do not sync. 

**Steps to reproduce**
1. Clean install of GOG GALAXY 2.0 (clear appData, clear programdata, clear program files)
2. Install steam plugin and login with an account (250+ games)
3. Wait for importing to be completed (and 15 minutes extra)
4. See that all game times are properly loaded, but achievements remain 0

**Expected behavior**
All achievements are loaded correctly

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4541642/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)
[Screenshot 1](https://user-images.githubusercontent.com/13137042/80412540-4f1a8500-88ce-11ea-9314-cd9095ba093a.png)
[Screenshot 2](https://user-images.githubusercontent.com/13137042/80412545-517cdf00-88ce-11ea-8b84-9c13ad5a947c.png)

I am experiencing this bug for months, so waiting does not help :s

**Comment by leebailey88** [comment]
Having this problem as well

**Comment by Danyelalejandro** [comment]
+1

**Comment by FriendsOfGalaxy** [comment]
Hi, logs tells me that everything is ok on plugin side. I can see you're achievements, for example for Portal2.

Please report this issue by Galaxy: cogwheel-menu -> Report Issue. Link problem from here, to let Gog people now that this is NOT the steam plugin issue.

**Comment by Tauron93** [comment]
I have reported this issue back in December 2019, and there is still no fix.

Not sure if this is a plugin issue or a galaxy issue: this issue only occurs for the steam integration, the achievements of the Xbox and Origin plugins work fine.

**Comment by FriendsOfGalaxy** [comment]
@Tauron93 attach you logs steam plugin logs again with `GalaxyClient.log` as I've described here: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files

I'll verify if this is GOG issue for 100% or not.

**Comment by Tauron93** [comment]
@FriendsOfGalaxy Thank you for verifying.

Here are my new logs (after doing the steps in my initial post): 

[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5147415/logs.zip)

**Comment by FriendsOfGalaxy** [comment]
Thanks for logs, I see there is a problem with achievement data structure on plugin side. Reopening

**Comment by Tauron93** [comment]
Today some achievements magically appeared, but not all of them. To me, this seems like a congestion somewhere. These are the logs I collected as soon as I saw the achievements appear.

[log-2020-11-17.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5555457/log-2020-11-17.zip)

When doing the steps in my initial post, all steam achievements are gone again.

**Comment by SCoppers-1** [comment]
@FriendsOfGalaxy Can you please confirm this issue is still being worked on?

**Comment by Tauron93** [comment]
I just wanted to let you all know that the recent commit that makes the message size larger did not fix this bug for me.

**Comment by Danyelalejandro** [comment]
Me neither. Bug is still happenning

**Comment by FriendsOfGalaxy** [comment]
Yes, not fixed yet, but high on my todo list now

**Comment by Tauron93** [comment]
Please let me know if there is anything I can do to help you (e.g. try your code on my set of games + achievements).

Also, I would like to debug the code and contribute to it. I am familiar with Git, typescript, Java and C++, but not yet with Python. What tools/setup do you use to develop and debug the plugin. Is there any way to add breakpoints for example?

**Comment by FriendsOfGalaxy** [comment]
@Tauron93 

Thanks for your offer. Definitely I would ask to test my fixes whenever it will got fixed.

Both things are in my backlog: fixing this bug and prepare/share debug tools to this repo.

For now I could only recommend debug by logs restarting Galaxy and modifying the code in %LocalAppData\GOG.com\Galaxy\plugins\installed 

(I know, this is sad, I'm sorry).

**Comment by Tauron93** [comment]
@FriendsOfGalaxy Thanks for the pointers. I took a deep dive into the code and discovered the following:

In my case, `protobuf_client._process_user_stats_response()` crashes on line 607 when processing the **train simulator** (game_id: 24010). Surely enough, all other achievements appeared when I skip this game using 

`if str(game_id) == "24010":`
   `continue`

While this does NOT fix the issue, we got a little bit closer to the root cause. 

@leebailey88 and @Danyelalejandro, can you please confirm you also own this game?

**Comment by Danyelalejandro** [comment]
> @FriendsOfGalaxy Thanks for the pointers. I took a deep dive into the code and discovered the following:
> 
> In my case, `protobuf_client._process_user_stats_response()` crashes on line 607 when processing the **train simulator** (game_id: 24010). Surely enough, all other achievements appeared when I skip this game using
> 
> `if str(game_id) == "24010":`
> `continue`
> 
> While this does NOT fix the issue, we got a little bit closer to the root cause.
> 
> @leebailey88 and @Danyelalejandro, can you please confirm you also own this game?

Thank you @Tauron93 Yes, I have that game in my Steam library

**Comment by leebailey88** [comment]
> @leebailey88 and @Danyelalejandro, can you please confirm you also own this game?

Hmm, I don't own Train Simulator

**Comment by Tauron93** [comment]
@leebailey88 and @Danyelalejandro, thank you for checking. If you have the time, can you please try this version of `protobuf_client.py`? (this code has an extra check to prevent crashes and will log more information) Unfortunatly I don't have any of the achievements myself, and I would like to know which other games have this issue.
[protobuf_client.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6213907/protobuf_client.zip)

1. Exit Galaxy 2.0
2. Paste it in C:\Users\XXXX\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_YYYYY\protocol
3. Clear al logs at C:\ProgramData\GOG.com\Galaxy\logs
4. Start Galaxy 2.0
5. Click sync integrations

Wait a few minutes and send the `plugin-steam-xxxxx.log` file back to me. Thanks!

**Comment by DarkWaterSong** [comment]
I am also having this issue, do you want any logs or files from me?  I have noticed the issue with every game I have played in the last few weeks from _GreedFall_ to _Isotiles_ to _Syberia The World Before - Prologue_ and more.

**Comment by Tauron93** [comment]
Actually, this particular issue should be fixed in the latest version of the plugin.

Can you try removing the plug-in from galaxy:

1. Logout from plug-in
2. Exit galaxy
3. Remove the plugin folder at C:\Users\XXXX\AppData\Local\GOG.com\Galaxy\plugins\installed\steam_YYYYY\
4. Open galaxy
5. Add steam plugin again.

If the issue still persists, yes please share the logs as described at https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files.

**Comment by DarkWaterSong** [comment]
I had steam_ca27391f-2675-49b1-92c0-896d43afa4f8 , and already tried disconnecting and re-connecting steam today.  Tried the folder removal, and now after getting GOG to re-download "0.58" I still have missing achievements and GreedFall actually got worse.  Now I have 0% instead everything from over a year ago.  Pulling the logs now.

**Comment by DarkWaterSong** [comment]
Let me know if you want anything else


[DarkWaterSong Logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/6401748/DarkWaterSong.Logs.zip)

**Comment by DarkWaterSong** [comment]
Update - I just checked and all the achievements and play sessions from the last few weeks loaded

**Comment by Silphatos** [comment]
Nothing past 0.52 worked for me so far, now I think even 0.52 can't import achievements anymore.

**Comment by FriendsOfGalaxy** [comment]
The fix from @Tauron93 was merged already. @DarkWaterSong thanks for confirmation that it works for you!

@Silphatos that is interesting, some optimizations were added in 0.53. Could you please create separate issue for that? Looks like a different problem. Attach logs from current version and the latest working one.
