### ISSUE TITLE
"Subscriptions" Sometimes Prioritized Over Ownership

### ISSUE THREAD

**Issue by SkyNinja** [FriendsOfGalaxy/galaxy-integration-steam#61]
**Describe the bug**
When a friend who shares their library with you also owns a game you own, the plugin sometimes classifies the game as a subscription, rather than being owned. This doesn't seem to happen with every game, however. For instance, I'm seeing Portal, Portal 2, Sega MegaDrive Classes, Sonic Adventure DX and Sonic All-Stars Racing Transformed in subscriptions, despite owning them, but I'm not seeing games such as Half-Life 2, Sonic Adventure 2, and others that we both own.

**Expected behavior**
Owned games are prioritized over Family Sharing.

**Log file**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4612903/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by FriendsOfGalaxy** [comment]
Hi,

I can see that plugin is sending Portal, Portal 2, Half-Life 2 and Sonic Adventure 2 (not checking the rest) as part of owned_games response. This means that plugin is sending correct data to the Galaxy Client. 

Not much i can do here, if you don't see games which you own in the owned games tab despite plugin sending them as owned then only people working on Galaxy can help you.
