### ISSUE TITLE
"Could not load the image"

### ISSUE THREAD

**Issue by Bobcat90** [FriendsOfGalaxy/galaxy-integration-steam#65]
I was having the "Offline. Retry" issue, so I tried syncing integrations (which didn't work), restarting Galaxy and eventually disconnecting and reconnecting the plugin. That solved the previous issue, but now some games show up as completely blank and I can't add a cover to them. This seems to mostly be games that don't have cover art in the database, because the others I can still change, and a couple are blank but still have the title, so I can change them. The ones that I can't change have a "Could not load the image" message where you would normally be able to click to change the cover.

I've attached a screenshot: ![image](https://user-images.githubusercontent.com/56528183/82374967-c0ee7600-9a17-11ea-81bf-1f0ad5091c5e.png)

And here is my Steam plugin log: 
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4652994/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

I saw a similar issue from August, but I don't think it's related to the 500 cover cap because I only have 235 games (163 in Steam), and I can still edit all games from other plugins.

**Comment by FriendsOfGalaxy** [comment]
Images for games, editing the covers etc is entirely on the side of Galaxy Client. The only thing plugin does here is provide the game titles.  Try writing a ticket here https://mantis2.gog.com
