### ISSUE TITLE
Login marks service as offline after a few days.

### ISSUE THREAD

**Issue by Pingger** [FriendsOfGalaxy/galaxy-integration-steam#67]
**Before start**
- **Checked** check if your issue is known: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Common-problems

**Describe the bug**
After a few Days of using GOG Galaxy, the Steam service is flagged as `offline` and can only be reconnected, by first disconnecting and the connecting the account again.
There is a reconnect button available, but that doesn't do a thing.
My guess: You try to often to use the (invalidated) token until the access with that token is blacklisted.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Log in with account.
2. Wait a few days. You may use the account in gog during this time
3. Steam is flagged as offline
![image](https://user-images.githubusercontent.com/4761298/83969034-a5b3af80-a8cd-11ea-86e3-5db3490c469a.png)

**Expected behavior**
Not have the service wrongly flagged as offline! Either call it "Lost connection" as previously and allow us to re-login or if the token is actually still valid, just use it.

**Attached logs**
https://pastebin.com/UqRNiEKS

By the way: It is bad manners to attach log files directly to a github post, because you would need to actually download that textfile before opening. usually other services are advised like gist, pastebin, ...

**Comment by Larnak1** [comment]
That's the same issue as discussed here, isn't it? 
https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/64

**Comment by Pingger** [comment]
yes sorry. I have  no idea how I missed that ...
