### ISSUE TITLE
Can't disconnect Steam account

### ISSUE THREAD

**Issue by TheTimmaeh** [FriendsOfGalaxy/galaxy-integration-steam#68]
**Describe the bug**
I can't disconnect my Steam account to connect a different account. When I hit "Disconnect", a confirmation window opens. After choosing "Confirm" instead of "Cancel" nothing happens. I can repeat this, restart/reinstall GOG Galaxy and the integration as often as I want, nothing changes.

**To Reproduce**
1. Log in with account
2. Decide to use different account
3. Open integrations settings
4. Search for Steam
5. Click "Disconnect" next to Steam
6. Hit "Confirm" in the confirm window

**Expected behavior**
After confirming, the connection should be reset.

**Attached logs**
[plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/4787257/plugin-steam-ca27391f-2675-49b1-92c0-896d43afa4f8.log)

**Comment by johnyb0y** [comment]
I can confirm this issue. Also tried deleting the integration folder under `AppData\Local\GOG.com\Galaxy\plugins\installed`.
GOGGalaxy just reinstalls the integration and starts syncing again.

**Comment by krugdenis** [comment]
I can confirm the issue too, also with Origin account. Can't disable both

**Comment by xuqingxin001** [comment]
I can't disconnect either

**Comment by FriendsOfGalaxy** [comment]
Hey @TheTimmaeh  @johnyb0y  @krugdenis  @xuqingxin001  
this is an issue with gog backends being overwhelmed. It should be reported here  https://mantis2.gog.com

**Comment by johnyb0y** [comment]
@FriendsOfGalaxy Thanks. Will do.
