### ISSUE TITLE
Error, delete this

### ISSUE THREAD

**Issue by OpenRift412** [FriendsOfGalaxy/galaxy-integration-steam#72]
**Before start**
- check if your issue is known: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Common-problems

**Describe the bug**

**To Reproduce**
<Remove this section if it's obvious>
Steps to reproduce the behavior, for example:
1. Log in with account that have 5k games
2. Wait 2 minutes
3. See that plugin has crashed

**Expected behavior**

**Attached logs**
Check how to do it properly: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files

**Comment by Chupaka** [comment]
@OpenRift412 please close this issue :)
