### ISSUE TITLE
Can't Use Integration on Multiple Devices

### ISSUE THREAD

**Issue by OpenRift412** [FriendsOfGalaxy/galaxy-integration-steam#73]
**Describe the bug**
I've noticed that when logging on to galaxy on multiple devices, I can only seem to use the Steam integration on just one device at a time. I don't know if this is because there isn't support for multiple devices, but other integrations don't seem to have this problem. If I try to disconnect and reconnect the integration on the other device, it will connect, but then the device that was already logged in starts to have the same problem that the newly logged in device was having.

**To Reproduce**
<Remove this section if it's obvious>
Steps to reproduce the behavior, for example:

1. Log onto device 1 and make sure Steam integration is connected.
2. Log onto device 2
3. Disconnect and reconnect integration on device 2.
4. Check device 1's connection status.

**Expected behavior**
It should be logged in on both devices without issue.

**Comment by FriendsOfGalaxy** [comment]
Thanks for description @OpenRift412 and sorry for late response

Issue is known (and most important now), I'm merging this with this one https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/81
