### ISSUE TITLE
Capitalization confussion of games

### ISSUE THREAD

**Issue by Maberi** [FriendsOfGalaxy/galaxy-integration-steam#83]
You may find two distinct games with the same name but not the same capitalization. That is the case for "Root" and "ROOT". The integration is showing the picture and description of "ROOT" and the game data of "Root"

**Comment by FriendsOfGalaxy** [comment]
This is Galaxy database problem. Please report to Galaxy issue tracker: https://mantis2.gog.com/bug_report_page.php
