### ISSUE TITLE
Unable to connect with two-factor auth enabled on steam.

### ISSUE THREAD

**Issue by Sztachu** [FriendsOfGalaxy/galaxy-integration-steam#88]
**Problem**
Steam backend responds with `AccountLogonDenied` (EResult==63) when connecting with two-factor auth enabled on steam.
[logs.txt](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5321137/logs.txt)

**To Reproduce**
1. Enable two-factor auth on steam
2. Try to connect
3. Enter username and password when asked
4. Enter valid auth code when asked

**Temporary fix**
Disabling two-factor auth on steam allows plugin to connect again.

**Comment by philou-felin** [comment]
I think I'm having a similar problem.

**Comment by FriendsOfGalaxy** [comment]
@philou-felin no problem.

@Sztachu - last release 0.56 should improve stability of connections in cases like this. Could you retest logging from the scratch?

**Comment by Sztachu** [comment]
@FriendsOfGalaxy Did some disconnects / connects with 2FA enabled on steam and I can confirm -  the problem is resolved.

**Comment by FriendsOfGalaxy** [comment]
Thanks for confirmation. I'm happy to close the issue now
