### ISSUE TITLE
Steam achievements not syncing anymore

### ISSUE THREAD

**Issue by Swampertrocks** [FriendsOfGalaxy/galaxy-integration-steam#92]
Hi,
I've been loving using The GOG galaxy launcher to combine all my PC libraries. Unfortunately my steam achievements stopped syncing. Even if I manually press Sync integrations. I decided to completely uninstall it and then reinstall it. And now I even lost achievements it counted before. I had 3000 achievements before I uninstalled it. And now after the reinstall it says I only have around 1000 achievements. However The playtime tracker still works fine. I hope you can help me to fix this. Thanks in advance.

**Comment by Silphatos** [comment]
Same problem here, I disconnected the plugin as it wasn't syncing the latest achievements for about a week. Now after the reconnect, it only synced ~3000 while I had ~6000 before.

**Comment by Krynh** [comment]
Same problem for me, none are syncing

**Comment by DogOnGH** [comment]
Same. Achievements didn't update in the last few days. As the others before me, I tried to disconnect and reconnect the plugin, plus manually reinstall it, and now it only updates achievements of games I played for the 1st time almost 4 years ago, right after I registered on Steam. All the achievements of games I played in the past 2-3 years aren't updating (0%).

**Comment by Silphatos** [comment]
So any update on this @FriendsOfGalaxy ?

**Comment by Swampertrocks** [comment]
It looks to me this is a widespread issue maybe @FriendsOfGalaxy you should fix this just saying.

**Comment by Pab10Suarez** [comment]
same here, i noticed that a new achievement i got in l4d2 didn't pop out in gog galaxy so i reconnected steam integration and now i don't have any achievement there in gog galaxy

**Comment by Swampertrocks** [comment]
@FriendsOfGalaxy are you gonna fix this issue or at least acknowledge it's an issue?

**Comment by Krynh** [comment]
Any updates on this @FriendsOfGalaxy ?

**Comment by UnperfectOne** [comment]
I can confirm I'm also having this issue.

**Comment by Swampertrocks** [comment]
Before I asked about this problem here. I asked the same question at GOG support directly. They answered within 24 hours and they told me to ask it here yet you guys seem to go the ignore route.

**Comment by DogOnGH** [comment]
@Swampertrocks I may be wrong, but at GOG they're payed for it (btw I contacted them first too and they never answered me), this is instead a community plugin. So, my piece of advice is to take it easy and be less demanding on whoever works on it, I tell you this because you sound kind of frustrated. I'm sure, eventually, someone will look into it and we will get our beloved numbers back (no sarcasm intended).

**Comment by Demitrix2k** [comment]
Same here as of current date

**Comment by Krynh** [comment]
@DogOnGH Not judging by the last update date on the files.

**Comment by Swampertrocks** [comment]
I did a reconnect of the steam plugin and now I lost all my steam achievements.

**Comment by Swampertrocks** [comment]
After clicking sync integrations a couple of times I got the achievements back that reappeared after the reinstall before (see first post). But all the "newer" achievements are still gone.

**Comment by NatParable** [comment]
I'm not getting any achievements either. Even if there's no update, it would be nice to have some communication from @FriendsOfGalaxy , at least some sort of acknowledgement of the issue.

**Comment by Swampertrocks** [comment]
Will this ever get fixed? :(

**Comment by Pab10Suarez** [comment]
I guess they're on vacation :c, i hope we soon see something about it

**Comment by Krynh** [comment]
In spite of the dev ignoring this there's a solution posted on the GoG Galaxy subreddit that implements the code from the pull requests for a new plugin files https://www.reddit.com/r/gog/comments/kqbewv/steam_plugin_achievement_fix_for_galaxy/?utm_medium=android_app&utm_source=share

**Comment by Swampertrocks** [comment]
Thanks @Krynh I downloaded the files put them in the right folders and that fixed it. Thank you so much 🥇

**Comment by Pab10Suarez** [comment]
That solution also worked for me, it just takes a bit to be applied

**Comment by FriendsOfGalaxy** [comment]
I'm sorry for being offline for long time. A new version with that fix was just released.

**Comment by Swampertrocks** [comment]
Well glad you fixed it for everybody
