### ISSUE TITLE
Achievements for specific games are ignored

### ISSUE THREAD

**Issue by kabamaru** [FriendsOfGalaxy/galaxy-integration-steam#96]
Even though achievements for Steam games can take a bit of time to show up on GOG Galaxy, there are specific games whose achievements will always show up as 0% no matter what. Here is a list of games I own that have this problem:

Amnesia: A Machine for Pigs
Back to Bed
Borderlands 2
Burly Men at Sea
Jotun: Valhalla Edition
Kholat
Layers of Fear
Little Nightmares
Rusty Lake Paradise
SOMA
Spec Ops: The Line
Styx: Master of Shadows
The Last Door: Season 2 - Collector's Edition (Season 1 works)
The Room Two (the original "The Room" works)
The Room Three
The Search

**Attached logs**
[logs.zip](https://github.com/FriendsOfGalaxy/galaxy-integration-steam/files/5665268/logs.zip)

**Comment by kabamaru** [comment]
Also, I don't know if it helps but, "Burly Men at Sea" is a game I played and finished on November 26-27th and got all the achievements. On GOG Galaxy it still shows 0%. The game's id is 403290.

**Comment by adakac** [comment]
Horizon Zero Dawn has the same problem.

**Comment by Silphatos** [comment]
Steam achievements are broken for weeks.
https://github.com/FriendsOfGalaxy/galaxy-integration-steam/issues/92

**Comment by Demitrix2k** [comment]
Seems like its all games

**Comment by kabamaru** [comment]
> 
> 
> Seems like its all games

Not for me. If you have this is happening to your entire library, maybe it's a different bug.

**Comment by Demitrix2k** [comment]
> Not for me. If this is happening to your entire library, maybe it's a different bug.

I have re-imported my entire library recently as an experiment, so this now affects my entire steam library

**Comment by kabamaru** [comment]
> 
> 
> > Not for me. If this is happening to your entire library, maybe it's a different bug.
> 
> I have re-imported my entire library recently as an experiment, so this now affects my entire steam library

Yeah, I've done the same. Disconnected from steam, re-imported library multiple times. Even uninstalled Galaxy, deleted every left over file, re-installed. It's always the same games for me.

**Comment by FriendsOfGalaxy** [comment]
@kabamaru the fix for general problem was just released. Please open Galaxy, wait some time to autoupdate your steam integration and check it again.

Let us know if the problem is solved or not. Thanks!

**Comment by kabamaru** [comment]
@FriendsOfGalaxy Good job, it worked beautifully. Thank you very much!

**Comment by Demitrix2k** [comment]
Works now, thank you.
