### ISSUE TITLE
Integration for Steam: Automatic updates?

### ISSUE THREAD

**Issue by hightower5** [FriendsOfGalaxy/galaxy-integration-steam#97]
Hi,

does the plugin get automatic updates? It seems that this update has a problem. Games are not synchronized.
There are a lot of messages in the "GOG Galaxy issue tracker". e.g.

```
0115472: Steam Installed games don't show.

hi!

My steam owned games do show up under owned games, but do not show up under installed games.
This means I still have to open up steam and that's not what I got GOG for. I wanted to be able to play
all my games from 1 spot.
```

```
0115688: Steam Games not in Library
The games from my integrated Steam account are not showing up in my GOG Galaxy Library.

```
The last plugin "Release version v0.53" works without problems.

Best regards

Hightower

**Comment by FriendsOfGalaxy** [comment]
Hi, updating plugin is up to Galaxy. Yes - it should autoupdate based on `currentversion.json`.

I'm not reading issues from GOG Galaxy issue tracker now. The only way to get less-known issue tracked is to post it here.
