### ISSUE TITLE
Memory Leak in Python process for GOG Galaxy on MacOS

### ISSUE THREAD

**Issue by sgreadly** [FriendsOfGalaxy/galaxy-integration-steam#99]
I've been directed here by GOG Support.

I noticed GOG Galaxy (Several versions throughout the past few months including 2.0.23 (3) and latest 2.0.33 (23) ) on my Catalina 10.15.7 & Big Sur 11.1 is leaking memory for Python process. It would be around ~700MB mark. A day later it climbs up to 1.13GB, and counting.. It's a slow leak - around ~100kb every ~15 seconds.

Eventually GOG Galaxy becomes unresponsive (and other unrelated apps unstable) when I hit OOM.

I'm not doing anything at all (not playing games etc.. it was weekend and I was away so it was just sitting idle).

**To Reproduce**

Simply start GOG Galaxy and leave it as-is. 

I believe you also need to connect with **Steam integration**. I have Steam & Epic connected. I have ~145 games owned across the 3 platforms.

**Expected behavior**

Memory to not leak / climb up to OOM.

**Attached logs**

[Screen Shot 2020-10-19 at 11.17.34 AM.png](https://support.gog.com/attachments/token/xIP4W3x99DaY0dWalLgjhgcDi/?name=Screen+Shot+2020-10-19+at+11.17.34+AM.png)
[Screen Shot 2020-10-19 at 11.17.39 AM.png](https://support.gog.com/attachments/token/qQTzwBJaS4nr6EQAGiaMqPMaS/?name=Screen+Shot+2020-10-19+at+11.17.39+AM.png)
[open_files_and_ports.txt](https://support.gog.com/attachments/token/O3xtIngOdgzl5sNe6Qkm6ajLm/?name=open_files_and_ports.txt)
[sample_text.txt](https://support.gog.com/attachments/token/ptKoizGoHgOuViaC9lQ21mRHV/?name=sample_text.txt)
[Log files](https://support.gog.com/attachments/token/44eJQpl54Nj9m0V0tJakPeKuM/?name=Logs.zip)

Check how to do it properly: https://github.com/FriendsOfGalaxy/galaxy-integration-steam/wiki/Log-files

Ta.

**Comment by sgreadly** [comment]
Hi,

Just checking for an update to this if possible?

Issue is still here on 2.0.35 (19).

**Comment by FriendsOfGalaxy** [comment]
Hi, I'm working on this, but cannot figure out leaking objects yet.

**Comment by sgreadly** [comment]
Thanks for the update! Let me know if there's anything else you need from my end.. debug, data, etc :) Wondering if there's a way to generate a core dump if that helps?

**Comment by FriendsOfGalaxy** [comment]
@sgreadly does it reproduce every time on your Mac? I've got some leaks on Windows, but it looks pretty random - after one Galaxy restart memory grows, after another - not.

**Comment by FriendsOfGalaxy** [comment]
@EP01
Could you please check if the memory leak occurs for you every time as well? If not - I would appreciate detailed steps scenario - maybe I'm missing something.

**Comment by sgreadly** [comment]
@FriendsOfGalaxy Yep, to me it happens every time. Note though that the Mac Mini has been retired yesterday. I moved to a 2013 MacBook Air, will test that one and see if the leak is also present next week and let you know.

**Comment by EP01** [comment]
@FriendsOfGalaxy Unfortunately I cannot be much help here, as (since you fixed the plugin crashes for me) the Galaxy client now crashes during the import of my Steam library. I've reported it to GOG every time through the automated crash report with my email address, but not heard anything back; so not looking likely that I can use it for my Steam library anytime soon.

**Comment by sgreadly** [comment]
Hmm,

The bad news is I can't seem to reproduce this anymore in my Macbook Air.. I see 3 Python daemons running instead of the one (in Mac Mini), and they're stable at ~50MB each.

**Comment by sgreadly** [comment]
Unfortunately I still cannot reproduce this, even on an M1 MBA.. Unless anyone else can or does share these symptoms, I suppose you'd close it until I or others can reproduce again.. :/ 

Thanks for the support so far.

**Comment by sgreadly** [comment]
Closing as I can't reproduce this, and later versions came out.
